### ISSUE TITLE
colour

### ISSUE THREAD

**Issue by RacingAce** [Mr-Bamboo-Forest/Link-Manager#9]
Links are very red.... kinda hard on the eyes

**Comment by Mr-Bamboo-Forest** [comment]
i agree, what color should i change them to, any recommendations?

**Comment by RacingAce** [comment]
idk anything else other than red

**Comment by Mr-Bamboo-Forest** [comment]
brrrrrrrrr

**Comment by Mr-Bamboo-Forest** [comment]
no
